name: Manual Upload

env:
  PROJ_NAME: sphinx-simplepdf

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: build dist files
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.file_list.outputs.files }}

    steps:
    - name: Install upload tools
      run: |
        sudo apt-get update
        pip install coscmd tccli

    - name: Configure COSCMD
      run: |
        coscmd config -a ${{ secrets.COS_DOCS_SECRET_ID }} -s ${{ secrets.COS_DOCS_SECRET_KEY }} -b ${{ secrets.COS_DOCS_BUCKET }} -r ${{ secrets.COS_DOCS_REGION }}

    - name: Upload artifacts to COS
      run: |
        VERSION=${{ github.ref_name }}
        # 定义版本号列表
        versions=(
          "1.6.0+sifli.1"
        )

        # 遍历版本号列表
        for version in "${versions[@]}"; do
          echo "Processing version: $version"

          # 定义文件列表
          files=(
            "https://github.com/OpenSiFli/sphinx-simplepdf-sifli/releases/download/v${version}/sphinx_simplepdf-${version}-py3-none-any.whl"
            "https://github.com/OpenSiFli/sphinx-simplepdf-sifli/releases/download/v${version}/sphinx_simplepdf-${version}.tar.gz"
          )

          # 下载文件
          mkdir -p dist/$version
          for url in "${files[@]}"; do
            echo "Downloading $url"
            curl -L -o "dist/$version/$(basename $url)" "$url"
          done

          # 上传文件到 COS
          # coscmd upload -rs --delete --yes dist/${version} tools/${PROJ_NAME}/v${version}/
          coscmd upload -rs --delete --yes dist/${version}/sphinx_simplepdf-${version}-py3-none-any.whl tools/sphinx-simplepdf/latest/sphinx_simplepdf-$latest-py3-none-any.whl
          coscmd upload -rs --delete --yes dist/${version}/sphinx_simplepdf-${version}.tar.gz tools/sphinx-simplepdf/latest/sphinx_simplepdf-$latest.tar.gz
        done
        echo "All versions processed and uploaded."

    - name: Purge CDN Cache
      run: |
        export TENCENTCLOUD_SECRET_ID=${{ secrets.COS_DOCS_SECRET_ID }}
        export TENCENTCLOUD_SECRET_KEY=${{ secrets.COS_DOCS_SECRET_KEY }}
        export TENCENTCLOUD_REGION=${{ secrets.COS_DOCS_REGION }}
        tccli cdn PurgePathCache --cli-unfold-argument --Paths "https://downloads.sifli.com/tools/${PROJ_NAME}/" --FlushType flush

